apiVersion: v1
kind: Pod
metadata:
  name: two-network
  namespace: dockin
  labels:
    env: test
spec:
  spec:
  containers:
    - args:
      command:
        - /bin/sh
        - -c
        - tail -f /dev/null
      image: busybox
      imagePullPolicy: IfNotPresent
      name: two-network
  nodeName: kube-node01